name: Test Parry

on:
  workflow_dispatch:
#  pull_request:
#    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code.
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install alsalib headers
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: taiki-e/install-action@nextest
      - name: Test with nextest
        run: cargo nextest run --no-default-features --features "parry3d" --test parry3d --profile ci
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: 'target/nextest/ci/junit.xml'
          retention-days: 1