name: Test Rapier

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code.
      uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install alsalib headers
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: Run tests for repository.
      run: cargo test --features "rapier"
